import jsonschema

from app.logger import get_logger
from app.tools.rag_search import rag_search
from app.tools.registry import TOOL_REGISTRY, get_tool
from app.tools.web_search import web_search

log = get_logger(__name__)

# Wire real handlers into the registry.
# This must happen after imports — not at module load in registry.py —
# to avoid circular imports between registry and handler files.
TOOL_REGISTRY["web_search"].handler = web_search
TOOL_REGISTRY["rag_search"].handler = rag_search


async def dispatch(tool_name: str, tool_input: dict) -> dict:
    """
    Validate and execute a tool call generated by the LLM.

    This is the only function the agent loop calls to execute tools.
    It never raises exceptions — all failures return {"error": "..."}.

    Args:
        tool_name:  Name of the tool to call (from LLM output).
        tool_input: Parameters for the tool (from LLM output).

    Returns:
        Tool result dict, or {"error": "..."} on any failure.
    """
    # ── Step 1: Check tool exists in registry ─────────────────────────────────
    # Reject hallucinated tool names immediately.
    tool = get_tool(tool_name)
    if tool is None:
        available = list(TOOL_REGISTRY.keys())
        log.warning("unknown_tool_called", tool_name=tool_name, available=available)
        return {
            "error": f"Unknown tool: '{tool_name}'.",
            "available": available,
            "hint": "Use one of the available tools listed above.",
        }

    # ── Step 2: Validate parameters against JSON Schema ───────────────────────
    # Catches missing required fields and wrong types before execution.
    try:
        jsonschema.validate(instance=tool_input, schema=tool.schema)
    except jsonschema.ValidationError as e:
        log.warning("tool_validation_failed", tool_name=tool_name, error=e.message)
        return {
            "error": f"Invalid parameters for '{tool_name}': {e.message}",
            "hint": "Check the tool schema and fix the parameters.",
        }

    # ── Step 3: Execute the tool ───────────────────────────────────────────────
    # All exceptions are caught and returned as structured errors.
    # The agent loop continues — it does not crash on tool failures.
    log.info("tool_dispatched", tool_name=tool_name, input_keys=list(tool_input.keys()))
    try:
        result = await tool.handler(**tool_input)
        log.info("tool_completed", tool_name=tool_name)
        return result

    except Exception as e:
        log.error("tool_execution_failed", tool_name=tool_name, error=str(e))
        return {
            "error": f"Tool '{tool_name}' failed: {str(e)}",
            "hint": "This may be a transient error. Try again or use a different tool.",
        }
